server:
  context-path: /${spring.application.name}
  tomcat:
    accesslog:
      enabled: false
    basedir: .
  port: 8081

spring:
  application:
    name: order-gateway
  cache:
    type: none
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false

zuul:
  routes:
    foos:
      path: /foos/**
      url: http://localhost:8080/demo/test

client:
  default-uri: https://partner-qa02.ftdi.com/partners/FTDOrderService
  ssl:
    trust-store: classpath:jks/client-truststore.jks
    trust-store-password: client-truststore-p455w0rd
  auth:
    header:
      user-name: provide_test
      password: provide_test


logging:
  level:
    ROOT: INFO
    org.springframework.ws.client.MessageTracing: TRACE


service:
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
  git:
    enabled: true
  vip:
    enabled: true
  swagger:
    enabled: true
  logging:
    enabled: true





memcached:
  cache:
    servers: localhost:11211
    mode: static


management:
  security:
    enabled: false

hystrix:
  command:
    helloCommandKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 60000
      metrics:
        rollingStats:
          timeInMilliseconds: 180000
  threadpool:
    helloThreadPoolKey:
      coreSize: 30
      metrics:
        rollingStats:
          timeInMilliseconds:18000

